CREATE TABLE cite_book_map (
    cite_book_map_id SERIAL PRIMARY KEY,
    cite_book_id INT NOT NULL REFERENCES cite_book(cite_book_id),
    cite_book_map_yy VARCHAR(250) NOT NULL
);

INSERT INTO cite_book_map (cite_book_map_yy, cite_book_id)
SELECT v.yy, cb.cite_book_id
FROM (VALUES
('1 Chronicles', 'Dabry ha Yowmym 1'),
('1 Kings', 'Melekym 1'),
('1 Melekym', 'Melekym 1'),
('1 Shamuw''el', 'Shamuw''el 2'),
('1 Shamuw''el / He Listens to God / 1 Samuel', 'Shamuw''el 1'),
('2 Melekym', 'Melekym 2'),
('2 Samuel', 'Shamuw''el 2'),
('2 Shamuw''el', 'Shamuw''el 2'),
('2nd Chronicles', 'Dabry ha Yowmym 2'),
('Bamidbar', 'Bamidbar'),
('Bamidbar / By Questioning the Word / Numbers', 'Bamidbar'),
('Bamidbar / In Questioning the Word / Numbers', 'Bamidbar'),
('Bamidbar / In the Wilderness / Numbers', 'Bamidbar'),
('Bamidbar / Numbers', 'Bamidbar'),
('Bare''syth', 'Bare''syth'),
('Bare''syth / Beginning / Genesis', 'Bare''syth'),
('Bare''syth / Genesis', 'Bare''syth'),
('Bare''syth / Genesis / In the Beginning', 'Bare''syth'),
('Bare''syth / In the Beginning / Genesis', 'Bare''syth'),
('Chabaquwq', 'Chabaquwq'),
('Chabaquwq / Accept This / Habakkuk', 'Chabaquwq'),
('Chabaquwq / Embrace This / Habakkuk', 'Chabaquwq'),
('Chabaquwq / Habakkuk', 'Chabaquwq'),
('Chagay / My Feast / Haggai', 'Dabarym'),
('Dabarym', 'Dabarym'),
('Dabarym / Deuteronomy', 'Dabarym'),
('Dabarym / Words', 'Dabarym'),
('Dabarym / Words / Dabarym', 'Dabarym'),
('Dabarym / Words / Deuteronomy', 'Dabarym'),
('Dabarym Words / Deuteronomy', 'Dabarym'),
('Dabarym ha Yowmym / 2nd Chronicles', 'Dabry ha Yowmym 2'),
('Dabarym ha Yowmym / Words Concerning the Days / 2 Chronicles', 'Dabry ha Yowmym 2'),
('Dabarym ha Yowmym / Words of the Days / 2nd Chronicles', 'Dabry ha Yowmym 2'),
('Dabry ha Yowmym / 1 Chronicles', 'Dabry ha Yowmym 1'),
('Dabry ha Yowmym / 2 Chronicles', 'Dabry ha Yowmym 2'),
('Dabry ha Yowmym / Words of the Time / 1 Chronicles', 'Dabry ha Yowmym 1'),
('Dabry ha Yowmym / Words of the Time / 2 Chronicles', 'Dabry ha Yowmym 2'),
('Daniel', 'Dany''el'),
('Daniel / Daniel', 'Dany''el'),
('Daniel / My God is Judgmental / Daniel', 'Dany''el'),
('Dany''el', 'Dany''el'),
('Dany''el / Daniel', 'Dany''el'),
('Dany''el / God Judges / Daniel', 'Dany''el'),
('Dany''el / God Judges and Vindicates / Daniel', 'Dany''el'),
('Dany''el / God is Judgmental / Daniel', 'Dany''el'),
('Dany''el / God is My Means to Decide / Daniel', 'Dany''el'),
('Dany''el / God is My Means to Decide between Vindication and Condemnation / Daniel', 'Dany''el'),
('Dany''el / God is My Means to Judge / Daniel', 'Dany''el'),
('Dany''el / My God Judges / Daniel', 'Dany''el'),
('Dany''el / My God Judges, Condemns, and Vindicates / Daniel', 'Dany''el'),
('Dany''el / My God Judges, Vindicates, and Condemns / Daniel', 'Dany''el'),
('Dany''el / My God Vindicates and Condemns / Daniel', 'Dany''el'),
('Dany''el / My God is Judgmental / Daniel', 'Dany''el'),
('Dedication to the Mizmowr / Lyrics to be Sung / Psalm 3', 'Mizmowr'),
('Dedication to the Mizmowr / Psalm 3', 'Mizmowr'),
('Ezekiel', 'Yachezq''el'),
('Genesis', 'Bare''syth'),
('Howsha''', 'Howsha'''),
('Howsha'' / He Delivers / Hosea', 'Howsha'''),
('Howsha'' / He Frees / Hosea', 'Howsha'''),
('Howsha'' / He Liberates / Hosea', 'Howsha'''),
('Howsha'' / He Liberates and Saves / Hosea', 'Howsha'''),
('Howsha'' / He Liberates, Delivers, and Saves / Hosea', 'Howsha'''),
('Howsha'' / He Protects / Hosea', 'Howsha'''),
('Howsha'' / He Provides / Hosea', 'Howsha'''),
('Howsha'' / He Saves / Hosea', 'Howsha'''),
('Howsha'' / Hosea', 'Howsha'''),
('Howsha'' / Salvation / Hosea', 'Howsha'''),
('Mal''aky', 'Mal''aky'),
('Mal''aky / Messenger / Malachi', 'Mal''aky'),
('Mal''aky / My Messenger / Malachi', 'Mal''aky'),
('Mal''aky / My Messenger / Messenger / Malachi', 'Mal''aky'),
('Mashal', 'Mashal'),
('Mashal / Meaningful Sayings / Proverb', 'Mashal'),
('Mashal / Meaningful and Easy to Remember Sayings / Proverb', 'Mashal'),
('Mashal / Meaningful, Vivid, and Easy to Remember Sayings / Proverb', 'Mashal'),
('Mashal / Meaningful, and Easy to Remember Sayings / Proverb', 'Mashal'),
('Mashal / Memorable and Meaningful Sayings / Proverb', 'Mashal'),
('Mashal / Proverb', 'Mashal'),
('Mashal / Proverbs', 'Mashal'),
('Mashal / Word Pictures', 'Mashal'),
('Mashal / Word Pictures / Proverb', 'Mashal'),
('Mashal / Word Pictures / Proverbs', 'Mashal'),
('Melekym / 1 Kings', 'Melekym 1'),
('Melekym / 1 Kings:', 'Melekym 1'),
('Melekym / 2 Kings', 'Melekym 2'),
('Melekym / Kings and Rulers / 2 Kings', 'Melekym 2'),
('Melekym / Rulers / 1 Kings', 'Melekym 1'),
('Mizmowr', 'Mizmowr'),
('Mizmowr / Lyrics / Psalm', 'Mizmowr'),
('Mizmowr / Lyrics of a Song / Psalm', 'Mizmowr'),
('Mizmowr / Lyrics to Sing / Psalm', 'Mizmowr'),
('Mizmowr / Lyrics to Songs / Psalm', 'Mizmowr'),
('Mizmowr / Lyrics to a Song / Psalm', 'Mizmowr'),
('Mizmowr / Lyrics to be Sung / Psalm', 'Mizmowr'),
('Mizmowr / Melodious Lyrics / Psalm', 'Mizmowr'),
('Mizmowr / Psalm', 'Mizmowr'),
('Mizmowr / Song / Psalm', 'Mizmowr'),
('Mizmowr / Song to Sing / Psalm', 'Mizmowr'),
('Mizmowr / Song with Lyrics / Psalm', 'Mizmowr'),
('Mykayah / Who Is Like Yah / Micah', 'Mykayah'),
('Nachemyah / Yah Comforts / Nehemiah', 'Nachemyah'),
('Nachemyah / Yahowah Comforts / Nehemiah', 'Nachemyah'),
('Psalm', 'Mizmowr'),
('Qara''', 'Qara'''),
('Qara'' / Called Out', 'Qara'''),
('Qara'' / Called Out / Leviticus', 'Qara'''),
('Qara'' / Invited to be Called Out and Meet / Leviticus', 'Qara'''),
('Qara'' / Leviticus', 'Qara'''),
('Ruth', 'Rut'),
('Shamuw''el', 'Shamuw''el 1'),
('Shamuw''el / 1 Samuel', 'Shamuw''el 1'),
('Shamuw''el / 1 Samuel 3', 'Shamuw''el 1'),
('Shamuw''el / 1st Samuel', 'Shamuw''el 1'),
('Shamuw''el / 2 Samuel', 'Shamuw''el 2'),
('Shamuw''el / He Listens to God / 1 Samuel', 'Shamuw''el 1'),
('Shamuw''el / He Listens to God / 2 Samuel', 'Shamuw''el 2'),
('Shamuw''el / Listen to Him / 1 Samuel', 'Shamuw''el 1'),
('Shamuw''el / Listen to Him / 2 Samuel', 'Shamuw''el 2'),
('Shaphat', 'Shaphat'),
('Shaphat / Decide / Judges', 'Shaphat'),
('Shaphat / Judges', 'Shaphat'),
('Shaphat / To Decide by Exercising Judgment / Judges', 'Shaphat'),
('Shemowth', 'Shemowth'),
('Shemowth / Exodus', 'Shemowth'),
('Shemowth / Exodus / Names', 'Shemowth'),
('Shemowth / Names', 'Shemowth'),
('Shemowth / Names / Exodus', 'Shemowth'),
('Shemowth / Names, Exodus', 'Shemowth'),
('Tsephanyah / Yahowah''s Treasures are Stored Up for Another Time / Zephaniah', 'Tsephanyah'),
('Yachezq''el', 'Yachezq''el'),
('Yachezq''el / Ezekiel', 'Yachezq''el'),
('Yahowsha''', 'Yahowsha'''),
('Yahowsha'' / Joshua', 'Yahowsha'''),
('Yahowsha'' / Yah Delivers / Joshua', 'Yahowsha'''),
('Yahowsha'' / Yah Liberates / Joshua', 'Yahowsha'''),
('Yahowsha'' / Yah Liberates and Saves / Joshua', 'Yahowsha'''),
('Yahowsha'' / Yah Saves', 'Yahowsha'''),
('Yahowsha'' / Yah Saves / Joshua', 'Yahowsha'''),
('Yahowsha'' / Yahowah Delivers / Joshua', 'Yahowsha'''),
('Yahowsha'' / Yahowah Delivers, Liberates, and Saves / Joshua', 'Yahowsha'''),
('Yahowsha'' / Yahowah Liberates / Joshua', 'Yahowsha'''),
('Yahowsha'' / Yahowah Liberates and Saves / Joshua', 'Yahowsha'''),
('Yahowsha'' / Yahowah Saves', 'Yahowsha'''),
('Yahowsha'' / Yahowah Saves / Joshua', 'Yahowsha'''),
('Yasha''yah', 'Yasha''yah'),
('Yasha''yah / Deliverance is from Yah / Isaiah', 'Yasha''yah'),
('Yasha''yah / Deliverance is from Yahowah / Isaiah', 'Yasha''yah'),
('Yasha''yah / Freedom and Deliverance are from Yahowah / Isaiah', 'Yasha''yah'),
('Yasha''yah / Freedom and Salvation are from Yah / Isaiah', 'Yasha''yah'),
('Yasha''yah / Freedom and Salvation are from Yahowah / Isaiah', 'Yasha''yah'),
('Yasha''yah / Freedom is from Yah / Isaiah', 'Yasha''yah'),
('Yasha''yah / Freedom is from Yahowah / Isaiah', 'Yasha''yah'),
('Yasha''yah / Isaiah', 'Yasha''yah'),
('Yasha''yah / Isiah', 'Yasha''yah'),
('Yasha''yah / Liberation and Salvation are from Yah / Isaiah', 'Yasha''yah'),
('Yasha''yah / Liberation and Salvation are from Yahowah / Isaiah', 'Yasha''yah'),
('Yasha''yah / Liberation is from Yah / Isaiah', 'Yasha''yah'),
('Yasha''yah / Salvation and Freedom Are from Yahowah / Isaiah', 'Yasha''yah'),
('Yasha''yah / Salvation is from Yah / Isaiah', 'Yasha''yah'),
('Yasha''yah / Salvation is from Yahowah / Isaiah', 'Yasha''yah'),
('Yasha''yah / Yah Delivers / Isaiah', 'Yasha''yah'),
('Yasha''yah / Yah Frees and Saves / Isaiah', 'Yasha''yah'),
('Yasha''yah / Yah Liberates / Isaiah', 'Yasha''yah'),
('Yasha''yah / Yah Liberates and Saves / Isaiah', 'Yasha''yah'),
('Yasha''yah / Yah Saves / Isaiah', 'Yasha''yah'),
('Yasha''yah / Yahowah Delivers / Isaiah', 'Yasha''yah'),
('Yasha''yah / Yahowah Delivers, Liberates, and Saves / Isaiah', 'Yasha''yah'),
('Yasha''yah / Yahowah Frees / Isaiah', 'Yasha''yah'),
('Yasha''yah / Yahowah Liberates / Isaiah', 'Yasha''yah'),
('Yasha''yah / Yahowah Liberates and Delivers / Isaiah', 'Yasha''yah'),
('Yasha''yah / Yahowah Rescues, Liberates, and Saves / Isaiah', 'Yasha''yah'),
('Yasha''yah / Yahowah Saves / Isaiah', 'Yasha''yah'),
('Yasha''yah / Yahowah''s Deliverance / Isaiah', 'Yasha''yah'),
('Yasha''yahuw / Freedom is from Yahowah / Isaiah', 'Yasha''yah'),
('Yasha''yahuw / Salvation is from Yahowah / Isaiah', 'Yasha''yah'),
('Yirmayah', 'Yirmayah'),
('Yirmayah / Jeremiah', 'Yirmayah'),
('Yirmayahuw / Rise Up and Live in Yah''s Shelter / Jeremiah', 'Yirmayah'),
('Yirmayahuw / Yah Lifts Up / Jeremiah', 'Yirmayah'),
('Yirma''yah', 'Yirmayah'),
('Yirma''yah / I Rise Up and Live in Yah''s Shelter / Jeremiah', 'Yirmayah'),
('Yirma''yah / Jeremiah', 'Yirmayah'),
('Yirma''yah / Respect Yah / Jeremiah', 'Yirmayah'),
('Yirma''yah / Respect Yahowah / Jeremiah', 'Yirmayah'),
('Yirma''yah / Respect and Revere / Jeremiah', 'Yirmayah'),
('Yirma''yah / Respect and Revere Yah / Jeremiah', 'Yirmayah'),
('Yirma''yah / Revere and Respect Yah / Jeremiah', 'Yirmayah'),
('Yirma''yah / Rise Up and Live in Yah''s Shelter / Jeremiah', 'Yirmayah'),
('Yirma''yah / Rise Up to Yah / Jeremiah', 'Yirmayah'),
('Yirma''yah / Yah Lifts Me Up / Jeremiah', 'Yirmayah'),
('Yirma''yah / Yah Lifts Me Up and Raises Me / Jeremiah', 'Yirmayah'),
('Yirma''yah / Yah Lifts Up / Jeremiah', 'Yirmayah'),
('Yirma''yah / Yah Raises and Lifts Up / Jeremiah', 'Yirmayah'),
('Yirma''yah / Yah Teaches / Jeremiah', 'Yirmayah'),
('Yirma''yah / Yah Teaches and Guides / Jeremiah', 'Yirmayah'),
('Yirma''yah / Yah Uplifts / Jeremiah', 'Yirmayah'),
('Yirma''yah / Yahowah Raises and Uplifts / Jeremiah', 'Yirmayah'),
('Yirma''yah / Yahowah Uplifts / Jeremiah', 'Yirmayah'),
('Yowb / Job', 'Yowb'),
('Yownah / Jonah', 'Yownah'),
('Yow''el', 'Yow''el'),
('Yow''el / Joel', 'Yow''el'),
('Yow''el / Joel / Yahowah is God / Joel', 'Yow''el'),
('Yow''el / Yah is God / Joel', 'Yow''el'),
('Yow''el / Yahowah is God / Joel', 'Yow''el'),
('Zakaryah', 'Zakaryah'),
('Zakaryah / Memorable Man of Yah / Zechariah', 'Zakaryah'),
('Zakaryah / Memorable Men of Yah', 'Zakaryah'),
('Zakaryah / Memorable Men of Yah / Zechariah', 'Zakaryah'),
('Zakaryah / Remember Yah', 'Zakaryah'),
('Zakaryah / Remember Yah / Zechariah', 'Zakaryah'),
('Zakaryah / Remember Yahowah', 'Zakaryah'),
('Zakaryah / Remember Yahowah /', 'Zakaryah'),
('Zakaryah / Remember Yahowah / Zechariah', 'Zakaryah'),
('Zakaryah / Remember Yahowah''s Memorable Men / Zechariah', 'Zakaryah'),
('Zakaryah / Zechariah', 'Zakaryah'),
('Zakaryah / Zechariah 9:7-10', 'Zakaryah'),
('Zakaryah 9', 'Zakaryah'),
('''Amows / Amos', '''Amows'),
('''Amows / Bearing a Burden / Amos', '''Amows')
) AS v(yy, hebrew)
JOIN cite_book cb ON cb.cite_book_hebrew = v.hebrew;
