<?php
/**
 * Detached CLI worker for "Initialize Transcript".
 *
 *   setsid php admin-transcript-init-worker.php <job_key> &
 *
 * admin-transcript-init.php enqueues a yy_feed_item_transcript_init_job row and
 * spawns this worker so the (heavy, ~60-230s on long episodes) promote runs
 * outside Cloudflare's ~100s proxy window. The work is identical to the old
 * synchronous endpoint: (re)assemble the hybrid join if needed, apply the
 * correction dictionary across rows, and replace the live transcript — using
 * the batched/trigger-skip fast path (see transcript-helpers.php). On finish it
 * flips the job to done/error and pg_notify()s 'transcript_init_<job_key>' so
 * admin-transcript-init-sse.php can push the result to the browser.
 *
 * No auth here — it's a local CLI process, not an HTTP request.
 */
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/transcript-helpers.php'; // applyCorrectionsAcrossRows, buildWhisperWordJoin, batchInsertRows

$jobKey = (int)($argv[1] ?? 0);
if (!$jobKey) { fwrite(STDERR, "usage: admin-transcript-init-worker.php <job_key>\n"); exit(1); }

$db = getDb();
// CLI worker is immune to the HTTP clock; don't let the request-scoped 120s
// statement_timeout kill a long batched insert on a very long episode.
try { $db->exec("SET statement_timeout = 0"); } catch (\Throwable $e) {}

// Single-worker editable-build queue: whenever this process ends (done, error,
// supersede-exit, or even a fatal), spawn the next pending init job so the
// queue drains one-at-a-time, in page order, server-side — surviving the
// operator closing the popover. Fresh connection: ours may be unusable at
// shutdown. The single-worker gate inside the helper prevents overlap.
register_shutdown_function(function () {
    try { spawnNextInitWorker(getDb()); } catch (\Throwable $e) {}
});

// Atomically claim the job so a double-spawn can't run it twice; stamp
// job_started so the dispatcher's reaper can tell how long it's been running.
$claim = $db->prepare("UPDATE yy_feed_item_transcript_init_job SET job_status='running', job_started=now()
                        WHERE job_key=? AND job_status='pending' RETURNING *");
$claim->execute([$jobKey]);
$job = $claim->fetch();
if (!$job) { exit(0); }   // already claimed, or gone (shutdown handler still pokes the queue)

$itemKey = (int)$job['job_item_key'];
$model   = (string)$job['job_model'];
$userKey = (int)$job['job_user_key'];

$notify = function (string $payload) use ($db, $jobKey) {
    try { $db->prepare("SELECT pg_notify(?, ?)")->execute(['transcript_init_' . $jobKey, $payload]); }
    catch (\Throwable $e) {}
};
$fail = function (string $msg) use ($db, $jobKey, $notify) {
    try {
        $db->prepare("UPDATE yy_feed_item_transcript_init_job SET job_status='error', job_error=?, job_completed=now() WHERE job_key=?")
           ->execute([mb_substr($msg, 0, 500), $jobKey]);
    } catch (\Throwable $e) {}
    $notify('error');
};

try {
    if ($userKey) { setCurrentUser($db, $userKey); }

    // ── Consensus mode: majority vote across several baselines, then re-flow
    //    into editable rows by the supplied caption params (see init endpoint). ──
    if ($model === 'consensus') {
        require_once __DIR__ . '/transcript-compare-lib.php';
        require_once __DIR__ . '/transcript-caption-lib.php';
        $jp = json_decode((string)($job['job_params'] ?? ''), true) ?: [];
        $baselines = array_values(array_filter((array)($jp['baselines'] ?? [])));
        $params    = (array)($jp['params'] ?? []);
        if (!$baselines) throw new Exception('consensus: no baselines supplied');
        // Server-side chain: block until the baselines still being generated by
        // this run land in _auto, so the editable transcript builds even if the
        // operator closed the popover. Bounded wait; then build with whatever
        // landed. (This worker holds no DB locks while sleeping.)
        $waitFor = array_values(array_filter((array)($jp['wait_for'] ?? [])));
        if ($waitFor) {
            // Wait while the still-missing baselines are ACTIVELY being generated
            // (their STT jobs are pending/running). Stop as soon as all have
            // landed, OR none of the missing ones is still active (they failed/
            // cancelled and won't come). ⚠ Replaces the old fixed 1h deadline,
            // which timed out — and errored "no baselines available" — when a
            // slow/deep STT queue took >1h to reach this item's baselines. A
            // generous absolute cap remains only as a stuck-queue safety net.
            $deadline = time() + 21600;   // 6h safety cap (single-worker gate guard)
            $wph = implode(',', array_fill(0, count($waitFor), '?'));
            while (true) {
                // Bail if a newer generation superseded this build (it flips our
                // status away from 'running'); avoids two workers racing to
                // overwrite the same live transcript.
                $cs = $db->prepare("SELECT job_status FROM yy_feed_item_transcript_init_job WHERE job_key = ?");
                $cs->execute([$jobKey]);
                if ($cs->fetchColumn() !== 'running') { $notify('cancelled'); exit(0); }
                $wq = $db->prepare("SELECT DISTINCT feed_item_transcript_auto_model FROM yy_feed_item_transcript_auto WHERE feed_item_key = ? AND feed_item_transcript_auto_model IN ($wph)");
                $wq->execute(array_merge([$itemKey], $waitFor));
                $missing = array_values(array_diff($waitFor, $wq->fetchAll(PDO::FETCH_COLUMN)));
                if (!$missing) break;   // all baselines landed
                // Are any of the missing baselines still being generated?
                $mph = implode(',', array_fill(0, count($missing), '?'));
                $aq2 = $db->prepare("SELECT COUNT(*) FROM yy_feed_item_transcript_job WHERE feed_item_key = ? AND job_model IN ($mph) AND job_status IN ('pending','running')");
                $aq2->execute(array_merge([$itemKey], $missing));
                if ((int)$aq2->fetchColumn() === 0) break;   // none still active → build with what landed
                if (time() >= $deadline) break;              // safety cap only
                sleep(4);
            }
            // Build only from baselines that actually exist now.
            $aph = implode(',', array_fill(0, count($baselines), '?'));
            $aq = $db->prepare("SELECT DISTINCT feed_item_transcript_auto_model FROM yy_feed_item_transcript_auto WHERE feed_item_key = ? AND feed_item_transcript_auto_model IN ($aph)");
            $aq->execute(array_merge([$itemKey], $baselines));
            $baselines = array_values(array_intersect($baselines, $aq->fetchAll(PDO::FETCH_COLUMN)));
            if (!$baselines) throw new Exception('consensus: no baselines available after waiting');
        }
        // Timing spine = best word-level baseline among those checked.
        $pref = ['gpu-whisperx-word','gpu-whisper-large-v3-word','gpu-whisper-large-v3-turbo-word','gpu-parakeet-tdt-0.6b-v2-word'];
        $spine = null;
        foreach ($pref as $c) if (in_array($c, $baselines, true)) { $spine = $c; break; }
        if (!$spine) foreach ($baselines as $c) if (strpos($c, '-word') !== false) { $spine = $c; break; }
        if (!$spine) $spine = $baselines[0];
        // Operator-chosen Primary overrides the preference-list pick: it becomes
        // the spine (text + word-timing guidance) when it's among the baselines.
        $primary = trim((string)($jp['primary'] ?? ''));
        if ($primary !== '' && in_array($primary, $baselines, true)) $spine = $primary;
        $refs = array_values(array_diff($baselines, [$spine]));
        $cmp = buildComparison($db, $itemKey, $spine, $refs);
        if (isset($cmp['error'])) throw new Exception('consensus: ' . $cmp['error']);
        $stream = [];
        foreach ($cmp['slots'] as $sl) { $w = trim((string)$sl['consensus']); if ($w !== '') $stream[] = ['t' => $sl['t'], 'w' => $w]; }
        if (!$stream) throw new Exception('consensus: empty word stream');
        $opts = [
            'max_chars'   => (int)($params['max_chars'] ?? 42),
            'max_lines'   => (int)($params['max_lines'] ?? 2),
            'max_secs'    => (float)($params['max_secs'] ?? 7.0),
            'min_secs'    => (float)($params['min_secs'] ?? 1.2),
            'break_punct' => array_key_exists('break_punct', $params) ? (bool)$params['break_punct'] : true,
            'break_gap'   => (float)($params['break_gap'] ?? 0),
            'dedup'       => array_key_exists('dedup', $params) ? (bool)$params['dedup'] : true,
        ];
        if (!empty($params['use_boundaries']) || !empty($params['prioritize_primary_breaks'])) {
            // "Prioritize Breaks from Primary" → anchor caption breaks on the
            // spine (Primary) boundaries only; otherwise use the union of all
            // checked baselines' segment boundaries.
            $bsources = !empty($params['prioritize_primary_breaks']) ? [$spine] : $baselines;
            $bset = [];
            foreach ($bsources as $bcode) {
                $bs = $db->prepare("SELECT feed_item_transcript_segment::text AS seg FROM yy_feed_item_transcript_auto WHERE feed_item_key = ? AND feed_item_transcript_auto_model = ?");
                $bs->execute([$itemKey, $bcode]);
                foreach ($bs->fetchAll(PDO::FETCH_ASSOC) as $br) $bset[] = round(cfIntervalToSecs($br['seg']), 2);
            }
            $bset = array_values(array_unique($bset)); sort($bset);
            $opts['boundary_set'] = $bset;
        }
        $cues = cfReflow($stream, $opts);
        if (!$cues) throw new Exception('consensus: re-flow produced no cues');
        // Surface the segment count to the queue monitor as soon as it's known
        // (status still 'running' — the final value is rewritten on 'done').
        try { $db->prepare("UPDATE yy_feed_item_transcript_init_job SET job_rows_written = ? WHERE job_key = ?")->execute([count($cues), $jobKey]); } catch (\Throwable $e) {}
        $notify('building:' . count($cues));
        $crows = [];
        foreach ($cues as $cue) {
            $crows[] = ['segment' => cfSecsToInterval((float)$cue['start']),
                        'text'    => str_replace("\n", ' ', (string)$cue['text'])];
        }
        $cleanedRows = applyCorrectionsAcrossRows($db, $crows);
    } else {
    // Derived hybrid models are assembled fresh from the current source feeds
    // every run, so a stale join can never reach the live transcript.
    if ($model === 'whisper-1-word-join' || $model === 'whisper-1-word-join-seg') {
        $useSeg = ($model === 'whisper-1-word-join-seg');
        $built = buildWhisperWordJoin($db, $itemKey, 'youtube', $useSeg);
        if ($built === 0) {
            $need = 'a word-level whisper + YouTube' . ($useSeg ? ' + a segment-level whisper' : '');
            throw new Exception('Cannot assemble ' . $model . ' — generate ' . $need . ' first.');
        }
    }

    $srcStmt = $db->prepare("
        SELECT feed_item_transcript_segment::text AS segment,
               feed_item_transcript_text          AS text,
               feed_item_transcript_sort          AS sort
          FROM yy_feed_item_transcript_auto
         WHERE feed_item_key = ?
           AND feed_item_transcript_auto_model = ?
         ORDER BY feed_item_transcript_sort, feed_item_transcript_segment
    ");
    $srcStmt->execute([$itemKey, $model]);
    $rows = $srcStmt->fetchAll();
    if (!$rows) throw new Exception('No rows in _auto for item=' . $itemKey . ' model=' . $model);

    // YadaYah enhancement: correction dictionary across the full row sequence
    // (multi-word substitutions that straddle row boundaries). Pure-PHP, done
    // before the transaction so the write window stays short.
    $cleanedRows = applyCorrectionsAcrossRows($db, $rows);
    }

    // Final supersede check before we touch the live transcript — if a newer
    // generation took over (status no longer 'running'), don't overwrite.
    $cs = $db->prepare("SELECT job_status FROM yy_feed_item_transcript_init_job WHERE job_key = ?");
    $cs->execute([$jobKey]);
    if ($cs->fetchColumn() !== 'running') { $notify('cancelled'); exit(0); }

    // Never overwrite a human-edited transcript. Overwrite is allowed only when
    // there's no live transcript yet, or its status is explicitly 'Pending'
    // (consensus-built, not edited). 'Editing' (or any non-Pending) is protected.
    $ps = $db->prepare("SELECT (SELECT COUNT(*) FROM yy_feed_item_transcript WHERE feed_item_key = ?) AS rown,
                               (SELECT edit_status FROM yy_feed_item_transcript_status WHERE feed_item_key = ?) AS st");
    $ps->execute([$itemKey, $itemKey]);
    $pr = $ps->fetch(PDO::FETCH_ASSOC);
    if ((int)$pr['rown'] > 0 && (string)($pr['st'] ?? '') !== 'Pending') {
        $fail('Editable transcript is protected (' . ($pr['st'] ?: 'edited') . ') — not overwritten.');
        exit(0);   // ⚠ must stop here — without it the build would overwrite the protected transcript
    }

    $db->beginTransaction();
    // Bulk-load fast path: suppress the live table's two per-row triggers
    // (tsv build + caption-queue mark) during the load, then replicate them
    // set-based. SET LOCAL reverts at transaction end.
    $db->exec("SET LOCAL session_replication_role = replica");

    $db->prepare("DELETE FROM yy_feed_item_transcript_autoclean WHERE feed_item_key = ? AND feed_item_transcript_autoclean_model = ?")
       ->execute([$itemKey, $model]);
    $db->prepare("DELETE FROM yy_feed_item_transcript WHERE feed_item_key = ?")
       ->execute([$itemKey]);

    $cleanRows = [];
    $liveRows  = [];
    $count = 0;
    $seen = [];   // (segment, text) → de-dupe; the live table has a UNIQUE
                  // (feed_item_key, segment, md5(text)) — uq_transcript_no_dup —
                  // and consensus re-flow can emit two identical cues at one
                  // timestamp, which would abort the whole batch insert.
    foreach ($cleanedRows as $i => $r) {
        $clean = mb_substr((string)$r['text'], 0, 2000);
        $dk = $r['segment'] . '|' . md5($clean);
        if (isset($seen[$dk])) continue;
        $seen[$dk] = true;
        $cleanRows[] = [$itemKey, $r['segment'], $clean, $i, $model];
        $liveRows[]  = [$itemKey, $r['segment'], $clean, $i, $userKey];
        $count++;
    }
    batchInsertRows($db,
        "INSERT INTO yy_feed_item_transcript_autoclean (feed_item_key, feed_item_transcript_segment, feed_item_transcript_text, feed_item_transcript_sort, feed_item_transcript_autoclean_model) VALUES",
        '(?, ?::interval, ?, ?, ?)', $cleanRows);
    batchInsertRows($db,
        "INSERT INTO yy_feed_item_transcript (feed_item_key, feed_item_transcript_segment, feed_item_transcript_text, feed_item_transcript_sort, feed_item_transcript_revision_user_key) VALUES",
        '(?, ?::interval, ?, ?, ?)', $liveRows);

    // Re-enable triggers and reproduce, set-based, exactly what
    // trg_yy_feed_item_transcript_tsv and trg_yy_feed_item_caption_queue
    // would have written per row.
    $db->exec("SET LOCAL session_replication_role = DEFAULT");
    $db->prepare("UPDATE yy_feed_item_transcript SET feed_item_transcript_tsv = to_tsvector('english', COALESCE(feed_item_transcript_text, '')) WHERE feed_item_key = ? AND feed_item_transcript_tsv IS NULL")
       ->execute([$itemKey]);
    $db->prepare("UPDATE yy_feed_item SET feed_item_yt_caption_status = 'queued' WHERE feed_item_key = ? AND COALESCE(feed_item_yt_caption_status, 'never') <> 'queued'")
       ->execute([$itemKey]);

    $db->commit();

    $db->prepare("UPDATE yy_feed_item_transcript_init_job SET job_status='done', job_rows_written=?, job_completed=now() WHERE job_key=?")
       ->execute([$count, $jobKey]);
    // A fresh consensus build is, by definition, not human-edited → 'Pending'
    // (overwritable). An admin editing it later flips it to 'Editing'.
    $db->prepare("INSERT INTO yy_feed_item_transcript_status (feed_item_key, edit_status, dtime)
                   VALUES (?, 'Pending', now())
                   ON CONFLICT (feed_item_key) DO UPDATE SET edit_status = 'Pending', dtime = now()")
       ->execute([$itemKey]);
    $notify('done:' . $count);
} catch (\Throwable $e) {
    if ($db->inTransaction()) $db->rollBack();
    error_log('admin-transcript-init-worker job ' . $jobKey . ' failed: ' . $e->getMessage());
    $fail($e->getMessage());
}
